using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            Stopwatch stopWatch = new Stopwatch();
            stopWatch.Start();

            bool
                found = false;
            float
                tmp1 = 0,
                tmp2 = 0;

            if (!found)
            {
                for (float x = 1; x < 50000; x++)
                {
                    if (!found)
                    {
                        for (float y = 1; y < x; y++)
                        {
                            tmp1 = ((float)Math.Sqrt(24 * ((x * (3 * x - 1) / 2) - (y * (3 * y - 1) / 2)) + 1) + 1) / 6;
                            tmp2 = ((float)Math.Sqrt(24 * ((x * (3 * x - 1) / 2) + (y * (3 * y - 1) / 2)) + 1) + 1) / 6;
                            if (Math.Floor(tmp1) == tmp1 && Math.Floor(tmp2) == tmp2 && tmp1 != tmp2 && !found)
                            {
                                found = true;
                                Console.WriteLine("{0}", ((x * (3 * x - 1) / 2) - (y * (3 * y - 1) / 2)));
                            }
                        }
                    }
                }
            }

            stopWatch.Stop();
            TimeSpan ts = stopWatch.Elapsed;

            string elapsedTime = String.Format("{0:00}:{1:00}:{2:00}.{3:00}",
                ts.Hours, ts.Minutes, ts.Seconds,
                ts.Milliseconds / 10);
            Console.WriteLine("RunTime " + elapsedTime);

            Console.ReadLine();
        }

    }
}
