using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

namespace Project_Euler___2
{
    class Program
    {
        static void Main(string[] args)
        {
            int 
                sum = 0,
                x = 1,
                y = 2,
                z = 0;

            while(x < 4000000)
            {
                z = x + y;
                sum = x % 2 != 0 ? sum : sum + x;
                x = y;
                y = z;
            }
            Console.WriteLine("sum: {0}", sum);
            Console.ReadLine();
        }
    }
}
